### ISSUE TITLE
Sentry 달기

### ISSUE THREAD

**Issue by YunYeoKyeong99** [YunYeoKyeong99/MoziServer#13]
## 목적
> Error, Exception 로그를 실시간으로 슬랙에서 확인해서 에러 대응을 한다.

## 작업 상세내용
- [x] Sentry 설정 추가
- [x] 슬랙알림 기능 추가

**Comment by JoHyoju04** [comment]
참고 : https://docs.sentry.io/platforms/java/guides/spring-boot/
