### ISSUE TITLE
일주일 챌린지가 일주일이 지나도 자동 완료 상태가 안되는 오류 수정하기

### ISSUE THREAD

**Issue by YunYeoKyeong99** [YunYeoKyeong99/MoziServer#33]
## 목적
> 일주일 챌린지가 일주일이 지나도 자동 완료 상태가 안되는 오류 수정하기

## 작업 상세내용
- [x] 배치 작업 코드 확인 

## 참고 사항

**Comment by JoHyoju04** [comment]
delete와 update 함수에 @transactional을 추가함으로서 해결함

**Comment by YunYeoKyeong99** [comment]
SheduleService의 updateUserChallengeDoingToEnd 메서드의
```Java
withTransaction(() -> {
                if (userChallenge.getTotalConfirmCnt() >= userChallenge.getChallenge().getRecommendedCnt()) {
                    userRewardRepository.incrementPoint(userChallenge.getUser().getSeq(), Constant.challengeExtraPoints);
                }
```
if문 실행시 rollback 발생

**Comment by YunYeoKyeong99** [comment]
```Java
userChallenge.getChallenge().getRecommendedCnt() 
``` 
에서 LazyInitializationException 발생

**Comment by YunYeoKyeong99** [comment]
userChallenge 와 연관관계인 challenge 엔티티가 LAZY LOADING이기 때문에 userChallenge.getChallenge.getRecommendedCnt() 실행시 LazyInitializationException발생 ->
QueryDSL에서 fetchJoin을 사용하여 UserChallnge 조회시 관련 Challenge 엔티티 정보 한번에 가져옴
