### ISSUE TITLE
가입시 도착하는 편지의 날짜 에러 수정

### ISSUE THREAD

**Issue by YunYeoKyeong99** [YunYeoKyeong99/MoziServer#4]
## 목적
> 편지 도착하는 날짜를 가입한 날짜로 정확하게 전달하기

## 작업 상세내용
- [  ] 목적과 동일

**Comment by JoHyoju04** [comment]
코드를 볼땐 문제가 없어보이는데 정확한 에러 확인을 위해 user_seq를 알려주세요 :)
