### ISSUE TITLE
confirm 삭제 API 호출시 DB에 deleted_confirm 테이블에 insert하는 로직 추가

### ISSUE THREAD

**Issue by JoHyoju04** [YunYeoKyeong99/MoziServer#40]
## 목적
> confirm 삭제 API를 했을 때 confirm 기록이 사라지므로 삭제 데이터를 관리할 수 있도록 함

## 작업 상세내용
- [ ] DB에 deleted_confirm 테이블 추가 
- [ ] confirm 삭제 로직 없애기
- [ ] deleted_confirm테이블 insert 함수 로직 추가

**Comment by YunYeoKyeong99** [comment]
애플리케이션 수정없이 임시적으로 confirm 테이블에서 삭제가 발생했을때 삭제된 데이터를 deleted_confirm에 저장하겠습니다.
